version: "3"

services:
    nginx:
        image: nginx:latest
        links: 
            - app:app
        volumes:
            - ./w-nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    app:
        build:
            context: .
        expose:
            - "5000"
        command: python -u /whitespace/w-app/app.py
        volumes:
            - ./w-app:/whitespace/w-app
        depends_on:
            - db
    db:
        image: mongo:3.4.2
    worker:
        build:
            context: celery-queue
            dockerfile: Dockerfile
        depends_on:
            - redis
    monitor:
        build:
            context: celery-queue
            dockerfile: Dockerfile
        ports:
            - "5555:5555"
        entrypoint: flower
        command:  -A tasks --port=5555 --broker=redis://redis:6379/0
        depends_on:
            - redis
    redis:
        image: redis